pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build (macos-latest, 16.x)
      - check-success=build (ubuntu-latest, 16.x)
      - check-success=build (windows-latest, 16.x)
    actions:
      merge:
        method: merge
