pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test (macos-latest, 20.x)
      - check-success=test (ubuntu-latest, 20.x)
      - check-success=test (windows-latest, 20.x)
      - check-success=lint
    actions:
      merge:
        method: merge
